'''
read([n]):读取n个字节或字符的内容返回，省略[n]读取所有
readline():读一行
readlines():每一行作为独立字符串对象，并将对象放入列表返回
write(str):
writelines(s_lst):将s_lst列表写入文本文件，不添加换行符
seek(offset[,whence]):
tell():返回指针的当前位置
flush():缓冲区内容写入文件，但不关闭文件
close():缓冲区内容写入文件，同时关闭文件，释放文件对象相关资源
'''