'''
append(element/lst):在列表末尾添加一个元素,lst作为一个元素
extend(lst):在列表末尾至少添加一个元素,lst作为多个元素
insert(index,element):在列表的任意位置添加一个元素
切片:在列表的任意位置至少添加一个元素，把指定区间切掉，换上新的多个元素
列表是在原列表上进行操作，不是操作后赋值给新变量
'''

lst=[10,20,30]
print(lst)
lst.append(100)
print(lst)
a=['NVIDIA',4090,'RTX','GPU']
lst.extend(a)
print(lst)
lst.insert(4,618)
print(lst)
lst[2:6]=a
print(lst)