'''
abspath(path):获取文件或目录的绝对路径
exists(path):判断文件或目录是否存在，存在返回True
join(path,name):将目录与目录或目录与文件名拼接起来
splite()：分离将路径与文件名
splitext():分离文件名和扩展名
basename(path):从一个路径中提取文件名
dirname(path):从一个路径中提取实际文件的上一级路径，仅把文件名去掉
isdir(path):判断是否为路径
'''